name: Dev
on:
  push:
    branches-ignore:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint
        uses: moorara/actions/go-lint@master
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: moorara/actions/go-cover@master
        with:
          codeclimate_reporter_id: ${{ secrets.CODECLIMATE_REPORTER_ID }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: moorara/actions/semver@master
      - name: Build
        uses: moorara/actions/cherry@master
        with:
          args: build -cross-compile=false
